/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include "InfixCalculator.h"

int *
eval_1_svc(char **argp, struct svc_req *rqstp)
{
  static int  result;

  result = EvalInfixExp(*argp);

  return &result;
}

