/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>

#include "calc.h"

#define MAX_EXP_LEN (1 << 15)


void
calc_prog_1(char *host)
{
  CLIENT *clnt;
  int  *result_1;
  char *eval_1_arg;

#ifndef	DEBUG
  
  clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
  
  if (clnt == NULL) 
  {
    clnt_pcreateerror (host);
    exit (1);
  }

#endif	/* DEBUG */

  eval_1_arg = calloc(MAX_EXP_LEN, sizeof(char));

  printf("Type expression : ");
  scanf("%s", eval_1_arg);

  result_1 = eval_1(&eval_1_arg, clnt);
  if (result_1 == (int *) NULL) 
  {
    clnt_perror (clnt, "call failed");
  }

  printf("The answer is %d\n", *eval_1_arg);

#ifndef	DEBUG

  free(eval_1_arg);
  clnt_destroy (clnt);

#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
  char *host;

  if (argc != 2) 
  {
    printf ("usage: %s server_host\n", argv[0]);
    exit (1);
  }
	
  host = argv[1];
	
  calc_prog_1 (host);
  
  exit (0);
}

