/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CALC_PROG 0x20000000
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define EVAL 1
extern  int * eval_1(char **, CLIENT *);
extern  int * eval_1_svc(char **, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define EVAL 1
extern  int * eval_1();
extern  int * eval_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
